Numpy is faster than list because it uses fixed types.
- Faster to read less bytes of memory
- uses contiguous (next or together in sequence) memory. 
- SIMD (Single instruction, multiple data) Vector Processing. 
- Effective Cache Utilization

In [49]:
import numpy as np
import os
os.chdir('C:\\Users\\DR_OM\\Z-Jupyter Extras')

In [2]:
a = np.array([1, 2, 3])
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(a), print(b)

# Get dimension
a.ndim, b.ndim

# Get shape
a.shape, b.shape

# Get data type
a.dtype, b.dtype

# Get size
a.itemsize, b.itemsize

# Get byte size
a.nbytes, b.nbytes

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


(12, 48)

In [3]:
c = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### Initializing Different Types of Arrays

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((4, 2, 2), dtype='float32') 

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)

In [6]:
# Set dimensions then value
np.full((2, 2), 69)

array([[69, 69],
       [69, 69]])

In [7]:
# full_like copies the dimensions of an existing matrix
#np.full_like(c, 69)
# or
#np.full(c.shape, 69)

In [8]:
# Random decimal numbers
np.random.rand(2,5)
np.random.random_sample(c.shape)

array([[0.50128061, 0.40808043, 0.92628524, 0.01364325, 0.77197096,
        0.48383634, 0.44166953],
       [0.75881201, 0.79953441, 0.24296688, 0.94105916, 0.44565983,
        0.87072147, 0.92599379]])

In [9]:
# Random Integer valeus
np.random.randint(10, size=[2,2])

array([[7, 4],
       [7, 3]])

In [10]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Repeat an array
arr = np.array([1, 2, 3])
r1 = np.repeat(arr, 3, axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [12]:
table1 = np.ones((5, 5))
table1[1:4,1:4] = np.zeros((3,3))
table1[2,2] = 9
table1



array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Be carefule when copying arrays

Need to use .copy() to prevent any changes that occur to new array, does not affect the original

In [13]:
a
e = a.copy()
e[1] = 22

### Linear Algebra

In [14]:
a1 = np.ones((2, 3))
a2 = np.full((3, 2), 2)
print(a1)
print(a2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [15]:
# Find the determinant
np.matmul(a1,a2)
adeter = np.identity(3)
np.linalg.det(adeter)

1.0

### Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

### Statistics

In [16]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [17]:
np.min(stats, axis=1)
np.max(stats, axis=1)

array([3, 6])

#### Reorganizing Arrays

In [18]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [19]:
# Vertically stacking vectors
v1 = before[0].copy()
v2 = before[1].copy()
vs = np.vstack([v1, v2])

h1 = np.zeros((3,2))
h2 = np.ones((3,3))
hs = np.hstack((h1, h2))
print(h1)
print(h2)
print(hs)

[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1.]]


In [27]:
file_data = np.genfromtxt('Numpypractice1.txt', delimiter=',')
file_data = file_data.astype('int32')

#### Boolean Masking and Advanced Indexing

In [29]:
file_data > 50
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [33]:
np.any(file_data > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [48]:
numbers = np.arange(1, 31)
numbers.shape
numbers_matrix = numbers.reshape((6,5))
print(numbers_matrix)
print(numbers_matrix[2:4, 0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
